[package]
name = "bloomrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1"
blake2  = "0.10.4"
fnv = "1.0.3"
base64ct = "1.5.0"
